image: Visual Studio 2022

skip_branch_with_pr: true
skip_tags: true
skip_commits:
  files:
    - '**/*.md'

install:
  - choco install dotnet-sdk --version 9.0.101

environment:
  Appveyor: true
  # Postgres
  POSTGRES_PATH: C:\Program Files\PostgreSQL\16
  PGUSER: postgres
  PGPASSWORD: Password12!
  POSTGRES_ENV_POSTGRES_USER: postgres
  POSTGRES_ENV_POSTGRES_PASSWORD: Password12!
  POSTGRES_ENV_POSTGRES_DB: test
  # MySQL
  MYSQL_PATH: C:\Program Files\MySQL\MySQL Server 8.0
  MYSQL_PWD: Password12!
  MYSQL_ENV_MYSQL_USER: root
  MYSQL_ENV_MYSQL_PASSWORD: Password12!
  MYSQL_ENV_MYSQL_DATABASE: test
  # Connection strings for tests:
  MySqlConnectionString: Server=localhost;Database=test;Uid=root;Pwd=Password12!
  OLEDBConnectionString: Provider=SQLOLEDB;Data Source=(local)\SQL2019;Initial Catalog=tempdb;User Id=sa;Password=Password12!
  PostgesConnectionString: Server=localhost;Port=5432;User Id=postgres;Password=Password12!;Database=test
  SqlServerConnectionString: Server=(local)\SQL2019;Database=tempdb;User ID=sa;Password=Password12!

init:
  - git config --global core.autocrlf input
  - SET PATH=%POSTGRES_PATH%\bin;%MYSQL_PATH%\bin;%PATH%
  - net start MSSQL$SQL2019
  - net start postgresql-x64-16
  - ps: Start-Service MySQL80
    
nuget:
  disable_publish_on_pr: true

before_build:
  # Postgres
  - createdb test
  # MySQL
  - '"C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql" -e "create database test;" --user=root'

build_script:
  # Our stuff
  - ps: .\build.ps1 -PullRequestNumber "$env:APPVEYOR_PULL_REQUEST_NUMBER" -CreatePackages $true

test: off
artifacts:
  - path: .\.nupkgs\*.nupkg
  
deploy:
- provider: NuGet
  server: https://www.myget.org/F/stackoverflow/api/v2
  on:
    branch: main  
  api_key:
    secure: P/UHxq2DEs0GI1SoDXDesHjRVsSVgdywz5vmsnhFQQY5aJgO3kP+QfhwfhXz19Rw
  symbol_server: https://www.myget.org/F/stackoverflow/symbols/api/v2/package
- provider: NuGet
  server: https://www.myget.org/F/dapper/api/v2
  on:
    branch: main  
  api_key:
    secure: PV7ERAltWWLhy7AT2h+Vb5c1BM9/WFgvggb+rKyQ8hDg3fYqpZauYdidOOgt2lp4
  symbol_server: https://www.myget.org/F/dapper/api/v2/package